ci:
  - changed-files:
      - any-glob-to-any-file: ".github/**/*"
apps:
  - changed-files:
      - any-glob-to-any-file: "applications/**/*"
github:
  - changed-files:
      - any-glob-to-any-file: "github-repos/**/*"
terraform:
  - changed-files:
      - any-glob-to-any-file: "modules/**/*"
