name: Labeler

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.FINURE_APP_ID }}
          private-key: ${{ secrets.FINURE_APP_KEY }}

      - name: Labeler
        uses: actions/labeler@v5
        with:
          repo-token: "${{ steps.app-token.outputs.token }}"
          configuration-path: .github/labeler-config.yaml
