name: "Terraform"

on: push

jobs:
  format:
    name: "Terraform Format"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changes
        run: |
          echo "::set-output name=tf-files::$(git diff-tree --diff-filter=ACMT --no-commit-id --name-only -r ${{ github.sha }} | grep .tf$ | xargs)"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        id: fmt
        run: |
          for file in ${{ steps.changes.outputs.tf-files }}; do
            terraform fmt -check $file
          done
